
[colors.primary]
background = "#083344" # Deep ocean navy blue
foreground = "#dce7ea" # Clean, beautiful ice-white

[colors.normal]
black = "#1c1f3a"
red = "#ff5c5c"
green = "#00e676"
yellow = "#ffb300"
blue = "#00b0ff"
magenta = "#d500f9"
cyan = "#00e5ff"
white = "#b0bec5"

[colors.bright]
black = "#546e7a"
red = "#ff1744"
green = "#69f0ae"
yellow = "#ffd740"
blue = "#40c4ff"
magenta = "#f50057"
cyan = "#18ffff"
white = "#ffffff"

[colors.vi_mode_cursor]
cursor = "#00d7ff"       # Vibrant electric cyan
text = "CellBackground"

[font]
size = 14

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFM"
style = "Medium"

[font.italic]
family = "JetBrainsMono NFM"
style = "Medium"

[font.normal]
family = "JetBrainsMono NFM"
style = "Bold"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "A"
mode = "Vi"

[[keyboard.bindings]]
action = "Last"
key = 5
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = 13
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
