#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
bspc monitor -d I II III IV

bspc config border_width        3
bspc config window_gap          4

bspc config split_ratio          0.45
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color  "#2e3440"
bspc config active_border_color  "#88c0d0"
bspc config focused_border_color "#5e81ac"

feh --bg-fill /home/night/Downloads/wallpaper.jpg
